language: node_js
node_js:
  - '0.10'
  - '0.12.0'
  - '0.12'
  - iojs

script:
  # Test postinstall
  - rm -rf node_modules
  - npm install .
  - npm install

  # Test
  - npm test

  # Test global install
  - npm install . -g
  - vimlint
  - vimlint --help
  - vimlint --version
  - vimlint test/succeeded.vim
  - vimlint test/failed.vim; [ $? != 0 ]

after_success:
  - npm run coverage

env:
  global:
    secure: "bYfP25nebZwoiWjp3SSfYSKyTmNZHThI5P0MVSuFlFW3PyPPC+MmToYrzLZc6qe03We+dhV7FPMfM1QZmhTfBiaB21t7tkTYW7Krpri6nbNm6TNLlIv8/HUfPEwJur4FUph38z0hPlS9rgS8SqljvahGnxfVDhU3znUdm54Nqdg="

notifications:
  slack:
    secure: "dO/0YS9SQvozILiZfJ4YxdQIbod7Z6LMggxA0m75Xoz6vpPK6/hzoXArmGkbVvSV/9IS6D0s/DnLp4w/TXssq6PtrCJnyRiXd+P4tCCCYKbcxUUBEWefJc/zwYjqSjIr6CyBsnR+yymPkaPzZ6Dk1xHsSaELoZ8g6n+IWM1Gckg="

sudo: false
